package com.betting.server;

import com.betting.handler.Router;
import com.betting.service.SessionService;
import com.betting.service.StakeService;
import com.sun.net.httpserver.HttpServer;

import java.net.InetSocketAddress;
import java.util.concurrent.Executors;

/**
 * Start class
 * <p>
 * dependency list：
 * - com.sun.net.httpserver.HttpServer  （ HTTP Server in JDK）
 * - java.util.concurrent.*            （ConcurrentHashMap, Thread Pool, Time）
 * - java.security.SecureRandom        （session key, generated by coding）
 * <p>
 * compile & run：
 * javac -d out $(find src -name "*.java")
 * java  -cp out com.betting.server.Main
 */
public class BettingServerMain {

    private static final int PORT = 8001;

    public static void main(String[] args) throws Exception {
        SessionService sessions = new SessionService();
        StakeService stakes = new StakeService();

        HttpServer server = HttpServer.create(new InetSocketAddress(PORT), 256);
        server.createContext("/", new Router(sessions, stakes));

        // thread pool cache：created by require, release after do not handle business 60s
        server.setExecutor(Executors.newCachedThreadPool());
        server.start();

        System.out.println("Betting server running on http://localhost:" + PORT);
    }
}
